### PR TITLE
Remove GTK Style flag; fix #2117. Default to Fusion theme on Windows

### LINKED ISSUE #2117: GTKSTYLE: Not as broke as advertised - Conditions may apply - Update INSTALL doc.
> Note: This issue is a discussion now linked to from INSTALL doc general  future reference and to have a place to discuss it and track issues.
## Intro

When looking at [`-DWANT_GTKSTYLE=` text in our INSTALL doc](https://github.com/kvirc/KVIrc/blob/master/doc/INSTALL.txt#L446-L461) thers all this doom and gloom blaming it on GTK insanity.

[Following this comment by @minj](https://github.com/kvirc/KVIrc/issues/2113#issuecomment-241187426) I just had to test it at this time.
### INSTALL DOC claims
- Menus do not appear
- Scrollbars are invisible
- Cant show icons on menus
- Label background is fixed see https://github.com/kvirc/KVIrc/issues/2117#issuecomment-241208158
- interferes with KVIrc internal theming (unreadable text white text on white background)

Also see https://github.com/kvirc/KVIrc/issues/2117#issuecomment-241208158 for clarification on the original documented issues.
### Observations after testing
- Menus _appear_ and render just fine (2 exceptions)
- Scrollbars _are visible_
- Icons _can and are shown in menus_
- Label background (seems fine ~~idk what fixed or INSTALL doc meant~~ with the style tested.)
- Theres no unreadable text  on my tests (exception for interference with theme is selection bars and some tooltips hardcoded colors.)
- Some dark Icons arent quite visible (exception but needs improving)
#### Exceptions of which some should be fixed.
- [ ] 1.  Server connect button is unstyled
- [ ] 2.  Groupbox boundaries on settings menus aren't visible,
- [ ] 3.  Menu separators and other similar type separators aren't visible.
- [ ] 4.  Overrides KVIrc theme selected color (exception which seems fine anyway)
- [ ] 5. Some Tooltips look weird and some text hard to read **(because we customize them)** this is expected then but looks bad, some unreadable text depending on style.
- [ ] 6. DCC transfer progress indicator is unstyled. (probably customized also).
- [ ] 7. Some dark program Icons arent quite visible in a dark setting/

Things could be better but hardly critical or not a reason to disable GTKSTYLE  **_however_**

I _**suspect**_ this is heavily dependent on desktop used, perhaps even distro or version and themes used how well GTK style is implemented there.
### Test Environment  / Install

This was a minimal Ubuntu iso (64-bit) of xenial 16.04LTS with Gnome Desktop only and Cinnamon 3.0.7 added ontop, with Mint-Y-Dark themes downloaded as is from GitHub.

heres a loose look.

demo-ab

demo-ab

---

From #2118 the INSTALL doc was revised and points to this discussion for future usage.

### PR DESCRIPTION
**Pull request by ctrlaltca**
This is a followup of #2663

### CODE REVIEW

File: src/kvilib/config/KviBuildInfo.cpp [hunk 1]
```diff
@@ -88,11 +88,11 @@ const QStringList feature_list{
 #endif
 #ifdef COMPILE_ENCHANT_SUPPORT
 	"Enchant",
-#endif
-#ifdef COMPILE_ENABLE_GTKSTYLE
-	"GTK",
 #endif
 	"Qt5",
```
Comment (DarthGandalf) [inline src/kvilib/config/KviBuildInfo.cpp:92]: maybe put Qt5 to #else branch?

Comment (ctrlaltca) [reply src/kvilib/config/KviBuildInfo.cpp:92]: I kept Qt5 since some scripts may need it, eg. `/echo $features(Qt5)` to determine if  some features only available since Qt5 are present

Comment (DarthGandalf) [reply src/kvilib/config/KviBuildInfo.cpp:92]: Okay, but a comment which explains that would be useful

Comment (DarthGandalf) [reply src/kvilib/config/KviBuildInfo.cpp:92]: Done in 03a8df16588ab42b4f4a070fc665e7ccf512e89d
