### PR TITLE
Fix #2262

### LINKED ISSUE #2262: Recognise status prefixes on channel PRIVMSG messages.
This is currently done with `NOTICE` messages, but not `PRIVMSG`.
Many IRC servers allow sending messages to only members of a channel with a certain status or higher, which is indicated by prefixing the channel name with the mode prefix. Support for this is advertised by the ISUPPORT token `STATUSMSG`.

### Expected behavior
The message should be shown in the channel window, along with the prefix.

### Actual behavior
The message is treated as if it were a private message.

### Steps to reproduce the issue
1. Connect to any server and join any channel.
2. In the channel window, enter `/inject PRIVMSG @$chan.name :Test`.

### System information
```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.15063
System version: Windows 10 (x64) (Build 15063)
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.8.0
Qt theme: 

Build Info:
Build date: 2017-06-30 12:02:57 UTC
Sources date: 20170630
Revision number: git-7128-g52ef11254
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```

### PR DESCRIPTION
**Pull request by AndrioCelos**
#### Changes proposed
- Correctly check for channel mode prefixes on `PRIVMSG` messages.

### CODE REVIEW

File: src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp [hunk 1]
```diff
@@ -1572,7 +1570,7 @@ void KviIrcServerParser::parseLiteralNotice(KviIrcMessage * msg)
 	if(!chan)
 	{
 		// check if the channel has some leading mode prefixes
-		while((szTarget.length() > 0) && console->connection()->serverInfo()->isSupportedModePrefix(szTarget[0].unicode()))
+		while((szTarget.length() > 0) && console->connection()->serverInfo()->supportedStatusMsgPrefixes().indexOf(szTarget[0]) >= 0)
```
Comment (IceN9ne) [inline src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp]: `indexOf` should be changed to `contains`.

File: src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp [hunk 2]
```diff
@@ -909,9 +909,21 @@ void KviIrcServerParser::parseLiteralPrivmsg(KviIrcMessage * msg)
 		}
 	}
 
-	// Normal PRIVMSG
+	QString szOriginalTarget = szTarget;
+	QString szPrefixes;
+
+	// check if the channel has some leading mode prefixes
+	while((szTarget.length() > 0) && console->connection()->serverInfo()->supportedStatusMsgPrefixes().indexOf(szTarget[0]) >= 0)
```
Comment (IceN9ne) [inline src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp]: `indexOf` should be changed to `contains`.

**Comment by IceN9ne** [comment]
For reference per concern in IRC conversation:

> The server MUST NOT advertise a character in STATUSMSG which is also present in CHANTYPES (Section 4.5).

https://tools.ietf.org/html/draft-hardy-irc-isupport-00#section-4.18
